Name:           ros-indigo-bag-tools
Version:        0.0.1
Release:        0%{?dist}
Summary:        ROS bag_tools package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/bag_tools
Source0:        %{name}-%{version}.tar.gz

Requires:       console-bridge-devel
Requires:       ros-indigo-camera-calibration-parsers
Requires:       ros-indigo-cv-bridge
Requires:       ros-indigo-image-geometry
Requires:       ros-indigo-image-proc
Requires:       ros-indigo-message-filters
Requires:       ros-indigo-rosbag
Requires:       ros-indigo-rospy
Requires:       ros-indigo-sensor-msgs
Requires:       ros-indigo-stereo-image-proc
BuildRequires:  console-bridge-devel
BuildRequires:  ros-indigo-camera-calibration-parsers
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-cv-bridge
BuildRequires:  ros-indigo-image-geometry
BuildRequires:  ros-indigo-image-proc
BuildRequires:  ros-indigo-message-filters
BuildRequires:  ros-indigo-rosbag
BuildRequires:  ros-indigo-rospy
BuildRequires:  ros-indigo-sensor-msgs
BuildRequires:  ros-indigo-stereo-image-proc

%description
ROS tools and scripts related to bagfiles

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Tue Sep 23 2014 Miquel Massot <miquel.massot@uib.es> - 0.0.1-0
- Autogenerated by Bloom

